[package]
name = 'rst'
version = '0.2.0'
authors = [ 'Phil Schaf <flying-sheep@web.de>' ]

description = 'a reStructuredText parser and renderer'
license = 'GPL-3.0'

documentation = 'https://flying-sheep.github.io/rust-rst'
homepage = 'https://github.com/flying-sheep/rust-rst'
repository = 'https://github.com/flying-sheep/rust-rst.git'

[dependencies]
url = '0.5'
bitflags = '0.5'
unicode_categories = '0.1.0'
